class Config:
    WIDTH = 800
    HEIGHT = 600
    TARGET_INCREMENT = 400
    TARGET_PADDING = 30
    BG_COLOR = (0, 25, 40)
    LIVES = 3
    TOP_BAR_HEIGHT = 50
    LABEL_FONT_SIZE = 24
    LABEL_FONT_NAME = "timesRoman"
